version: 5.1.{build}.0
image: Visual Studio 2017

platform:
    - All

configuration:
    - Release

environment:
  LOGDLL: '"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"'

install:
    - cd "%APPVEYOR_BUILD_FOLDER%"
    - nuget restore TrimLineEnds\packages.config -PackagesDirectory packages

build_script:
    - cd "%APPVEYOR_BUILD_FOLDER%"
    - ps: >-
        . .\buildhelpers.ps1

        UpdateVsVersion TrimLineEnds $env:appveyor_build_version
    - msbuild TrimLineEnds.sln /m /p:configuration="Release" /p:platform="Any CPU" /logger:%LOGDLL%

after_build:
    - cd "%APPVEYOR_BUILD_FOLDER%"
    - ps: >-
        Push-AppveyorArtifact "TrimLineEnds\bin\$env:CONFIGURATION\TrimLineEnds.vsix" -FileName TrimLineEnds.vsix

deploy:
    provider: GitHub
    auth_token:
        secure: TA1/2G21wUBPSWRbmBul7xGvE3YpX8n8AEooMuwkiqhxGhD2bLJ0Y//rS7+qwIN1
    draft: true
    prerelease: false
    force_update: true
    on:
        branch: master
        appveyor_repo_tag: true
